name: Deploy Development Server.

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x, 15.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: Install dependencies
        run: npm ci
      - name: Setup environment
        env:
          NODE_ENV: dev
        run: |
          cd ..
          git clone https://${{secrets.MY_GITHUB_TOKEN}}@github.com/orbitalno11/${{secrets.SECRET_FILE_REPOSITORY}}.git
          cp ./${{secrets.SECRET_FILE_REPOSITORY}}/server/dev/serviceAccountKey.json ./get-a-server
          cp ./${{secrets.SECRET_FILE_REPOSITORY}}/server/dev/jwtRS256.key ./get-a-server
          cp ./${{secrets.SECRET_FILE_REPOSITORY}}/server/dev/jwtRS256.key.pub ./get-a-server
          cp ./${{secrets.SECRET_FILE_REPOSITORY}}/server/dev/{.env,.env.debug,.env.dev,.env.local} ./get-a-server
          cd ./get-a-server
      - name: Build app
        run: npm run build --if-present
      - name: Run Test
        run: npm test

  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy node app
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_KEY}}
          script: |
            cd ~/get-a-server
            git pull origin develop
            npm ci
            npm run build
            pm2 restart get-a-server
