name: Unit test

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Setup environment
      env:
        environment: dev
        dev_port: 9000
        prod_port: 9001
        db_host: ${{secrets.DB_HOST_DEV}}
        db_name: ${{secrets.DB_NAME_DEV}}
        db_user:  ${{secrets.DB_USER_DEV}}
        db_password: ${{secrets.DB_PASSWORD_DEV}}
      run: |
        cd ..
        git clone https://${{secrets.MY_GITHUB_TOKEN}}@github.com/orbitalno11/${{secrets.SECRET_FILE_REPOSITORY}}.git
        cp ./${{secrets.SECRET_FILE_REPOSITORY}}/FirebaseClient.ts ./get-a-server/configs/firebase
        cp ./${{secrets.SECRET_FILE_REPOSITORY}}/serviceAccountKey.json ./get-a-server/configs/firebase
        cp ./${{secrets.SECRET_FILE_REPOSITORY}}/jwtRS256.key ./get-a-server
        cp ./${{secrets.SECRET_FILE_REPOSITORY}}/jwtRS256.key.pub ./get-a-server
        cd ./get-a-server
    - name: Build app
      run: npm run build --if-present
    - name: Run Test
      run: npm test
